name: Build
on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check
        run: cargo check

      - name: Check fmt
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose